# -*- coding: utf-8 -*-
"""Tugas1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x0BDWfcdrRY6_ps3Hahx_20P-pvmuCqb

jumlahkan 2 bilangan
"""

# Program penjumlahan dua bilangan

# Meminta input dari pengguna
bilangan1 = int(input("Masukkan bilangan pertama: "))
bilangan2 = int(input("Masukkan bilangan kedua: "))

# Menjumlahkan bilangan
hasil = bilangan1 + bilangan2

# Menampilkan hasil
print("Hasil penjumlahan:", hasil)

#Program Mnejumlahkan Dua Bilangan

#Meminta input dari pengguna
Bil1 = int(input("Masukkan bilangan pertama: "))
Bil2 = int(input("Masukkan bilangan kedua: "))

#Menjumlahkan bilangan
hasil = Bil1 + Bil2

#Menampilkan hasil
print("hasil penjumlahan", hasil)

# Program cek umur pengguna

# Meminta input nama dan umur
nama = input("Masukkan nama Anda: ")
umur = int(input("Masukkan umur Anda: "))

# Mengecek apakah cukup umur
if umur >= 18:
    print(nama, "sudah cukup umur (dewasa).")
else:
    print(nama, "belum cukup umur.")